### ISSUE TITLE
ERROR: Unable to load plugin

### ISSUE THREAD

**Issue by VoidableMoon884** [cgaffga/mc-vhost#2]
[ERROR]: Unable to load plugin plugins/VirtualHostCommandPlugin-0.9.4.jar

com.velocitypowered.api.plugin.InvalidPluginException: The plugin file VirtualHostCommandPlugin-0.9.4.jar appears to be a Bukkit or BungeeCord plugin. Velocity does not support Bukkit or BungeeCord plugins.

	at com.velocitypowered.proxy.plugin.loader.java.JavaPluginLoader.getSerializedPluginInfo(JavaPluginLoader.java:154) ~[velocity-3.3.0-SNAPSHOT-312.jar:3.3.0-SNAPSHOT (git-00ef92bc-b312)]

	at com.velocitypowered.proxy.plugin.loader.java.JavaPluginLoader.loadCandidate(JavaPluginLoader.java:64) ~[velocity-3.3.0-SNAPSHOT-312.jar:3.3.0-SNAPSHOT (git-00ef92bc-b312)]

	at com.velocitypowered.proxy.plugin.VelocityPluginManager.loadPlugins(VelocityPluginManager.java:96) ~[velocity-3.3.0-SNAPSHOT-312.jar:3.3.0-SNAPSHOT (git-00ef92bc-b312)]

	at com.velocitypowered.proxy.VelocityServer.loadPlugins(VelocityServer.java:359) ~[velocity-3.3.0-SNAPSHOT-312.jar:3.3.0-SNAPSHOT (git-00ef92bc-b312)]

	at com.velocitypowered.proxy.VelocityServer.start(VelocityServer.java:241) ~[velocity-3.3.0-SNAPSHOT-312.jar:3.3.0-SNAPSHOT (git-00ef92bc-b312)]

	at com.velocitypowered.proxy.Velocity.main(Velocity.java:69) ~[velocity-3.3.0-SNAPSHOT-312.jar:3.3.0-SNAPSHOT (git-00ef92bc-b312)]

**Comment by cgaffga** [comment]
yes, it's a Bukkit, works well on papermc
