### ISSUE TITLE
Unable to load plugin :D

### ISSUE THREAD

**Issue by BluetoothWiFi** [cgaffga/mc-vhost#3]
```
[21:43:40 ERROR]: Unable to load plugin plugins/VirtualHostCommandPlugin-0.9.4.jar
com.velocitypowered.api.plugin.InvalidPluginException: The plugin file VirtualHostCommandPlugin-0.9.4.jar appears to be a Bukkit or BungeeCord plugin. Velocity does not support Bukkit or BungeeCord plugins.
        at com.velocitypowered.proxy.plugin.loader.java.JavaPluginLoader.getSerializedPluginInfo(JavaPluginLoader.java:164) ~[velocity.jar:3.3.0-SNAPSHOT (git-c34dafe2-b369)]
        at com.velocitypowered.proxy.plugin.loader.java.JavaPluginLoader.loadCandidate(JavaPluginLoader.java:64) ~[velocity.jar:3.3.0-SNAPSHOT (git-c34dafe2-b369)]
        at com.velocitypowered.proxy.plugin.VelocityPluginManager.loadPlugins(VelocityPluginManager.java:96) ~[velocity.jar:3.3.0-SNAPSHOT (git-c34dafe2-b369)]
        at com.velocitypowered.proxy.VelocityServer.loadPlugins(VelocityServer.java:364) ~[velocity.jar:3.3.0-SNAPSHOT (git-c34dafe2-b369)]
        at com.velocitypowered.proxy.VelocityServer.start(VelocityServer.java:241) ~[velocity.jar:3.3.0-SNAPSHOT (git-c34dafe2-b369)]
        at com.velocitypowered.proxy.Velocity.main(Velocity.java:70) ~[velocity.jar:3.3.0-SNAPSHOT (git-c34dafe2-b369)]
```

![image](https://github.com/cgaffga/mc-vhost/assets/67960469/02f67bb7-9db6-49e8-8757-51337470ca65)
What do you think about not misleading those who decided to download it? Or do this for velocity idk :0

**Comment by cgaffga** [comment]
oh, on modrinth it mentions velocity, that'S wrong, changed that. Sorry for the confusion

**Comment by BluetoothWiFi** [comment]
No problem, thanks for fast answer❤️
